=begin
Lista de Usuários

Essa api disponibiliza usuarios para acessar o sistema

OpenAPI spec version: 0.0.1
Contact: arthur.m.celedonio@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class User < ApplicationRecord
  validates_presence_of :email
  validates_presence_of :name

end
